openapi: '3.0.3'
info:
  title: TestMockServerApp
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Example
paths:
  /greet:
    get:
      operationId: getGreeting
      parameters:
      - name: name
        required: false
        in: query
        description: A name used in the returned greeting.
        schema:
          type: string
      responses:
        '200':
          description: A success response with a greeting.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Greeting'
  /image:
    get:
      operationId: getImage
      responses:
        '200':
          description: "Return image"
          content:
            image/png:
              schema:
                type: string
                format: binary
components:
  schemas:
    Greeting:
      type: object
      properties:
        message:
          type: string
      required:
        - message
